### ISSUE TITLE
Add additional transcoding options per files

### ISSUE THREAD

**Issue by fortin-mo** [wieslawsoltes/BatchEncoder#115]
First off, great job on what you've done so far :)

I've been using it for quite some times now and it works great and is quite easy to use. One thing I can think off that could make it better is to add an additional column where you can add additional options per file for transcoding. This would allow to add specific options without the need to create a seperate presets.

For exemple, if you have 10 files that need the exact same presets but 2 off them have a slight delay, you could just add the --delay options instead of creating 2 new presets for those 2 files.

Just like in the picture below

![batchencoder](https://user-images.githubusercontent.com/6748711/34827791-5525cb9e-f6a9-11e7-9c6a-ba394b72b4f4.jpg)

This could also be done with encoding options if needed.

Thanks :)

I cannot label but I guess it would go with Area-UI and Enhancement

**Comment by wieslawsoltes** [comment]
@mofortin Great idea.

**Comment by wieslawsoltes** [comment]
@mofortin Implemented additional options. This feature will be release as part of v2.3.

![2018-01-13_00-42-06](https://user-images.githubusercontent.com/2297442/34899723-ea33e354-f7fa-11e7-99ab-c7216ddc26fa.gif)
