### ISSUE TITLE
$OPTIONS not working since 3.0

### ISSUE THREAD

**Issue by fortin-mo** [wieslawsoltes/BatchEncoder#125]
Looks like $OPTIONS parameter is always empty ( not working ) in neither format or presets.

For example, transcoding WAV to M4A ( QAAC / HE ) will always use default settings, TVBR 91. This can be seen when enable the console.

**Comment by wieslawsoltes** [comment]
@mofortin Thanks for reporting. Fixed the issue, will release ASAP fixed version 3.1.

**Comment by wieslawsoltes** [comment]
@mofortin Version 3.1 was released with the fix.

**Comment by chros73** [comment]
Thanks @wieslawsoltes for this amazing converter tool! I've been searching a small but smart GUI for qaac, and yesterday I found yours.
I just wanted to report this issue, and I saw there's a new release which fixed it! :)
Great job, thanks!
