### ISSUE TITLE
ChangeLog

### ISSUE THREAD

**Issue by smaragdus** [wieslawsoltes/BatchEncoder#131]
[ChangeLog](https://github.com/wieslawsoltes/BatchEncoder/blob/master/CHANGELOG.md) is gone, please bring it back since it is easier to copy from it than from [Releases](https://github.com/wieslawsoltes/BatchEncoder/releases).

**Comment by wieslawsoltes** [comment]
@smaragdus it was moved here https://github.com/wieslawsoltes/BatchEncoder/wiki/Changelog Is this location ok?

**Comment by smaragdus** [comment]
@wieslawsoltes 
Thank you very much. Of course it is OK.
I would like to use this occasion to thank you for your excellent work on **BatchEncoder**!
Regards
