### ISSUE TITLE
Input extensions doesn't work under Configure Formats

### ISSUE THREAD

**Issue by chros73** [wieslawsoltes/BatchEncoder#154]
I wanted to mass transcode `flac` files into `m4a` with `qaac` (`qaac` can read `flac` directly, without the need to create an intermediate `wav` file), so I specified the following at `Output Formats -> M4A (MPEG-4/AAC) - qaac`:
- Input extensions: `WAV,FLAC`

But transcoding doesn't start:
- in Status column: Error: progress did not reach 100%
- and in the console window (probably): input format is not supported

I copied `libFLAC.dll` into `BatchEncoder-x64\tools\qaac_2.64\qaac_2.64\x64\` directory, and `qaac64.exe` uses it if you fire it up manually:
- `BatchEncoder-x64\tools\qaac_2.64\qaac_2.64\x64\qaac64.exe` *.flac

Thanks for this outstanding util!

**Comment by wieslawsoltes** [comment]
Thank you for reporting. Will investigate. Can you try test this issue with CI builds?

**Comment by chros73** [comment]
Of course, if you tell me how :)

**Comment by wieslawsoltes** [comment]
https://github.com/wieslawsoltes/BatchEncoder/wiki/CI-Builds

https://ci.appveyor.com/project/wieslawsoltes/batchencoder/build/artifacts

**Comment by wieslawsoltes** [comment]
https://ci.appveyor.com/project/wieslawsoltes/batchencoder/build/1680/artifacts

**Comment by chros73** [comment]
> build/1680

Yes, it's the same error with using the x64 build.

**Comment by wieslawsoltes** [comment]
@chros73 I have source of the issue. The qaac format is using input pipes to pipe input file to stdin, this works for WAV input, but when using FLAC it thinks its WAV and fails. The command-line you have used works because you have specified input file name and extension. To solve the issue uncheck if Configure Formats -> Pipes: -> Input. Please let me know if this helps.

![qaac_flac](https://user-images.githubusercontent.com/2297442/35474142-622f9188-038a-11e8-9f38-2cd9e0ce32a8.PNG)

**Comment by chros73** [comment]
Thanks, works like a charm with v3.1!
I tried out quickly with 4 files (2 `mp3` and 2 `flac`):
- using `qaac` encoder
- Input Extensions: `WAV,FLAC`
- Pipes: unset both

So it seems `qaac.exe` doesn't need pipes setting at all in its format profile.

Thank You, Wieslaw, for the quick response!

PS: I'll raise 2 minor issues now, but these can wait.

**Comment by wieslawsoltes** [comment]
@chros73 Greate.

> So it seems qaac.exe doesn't need pipes setting at all in it's format profile.

It does not on itself, but its usefull when using it with other decoder so I can pipe decoder output to encoder input pipe. Unfortunately not all decoder support pipes and if so there are issues like you can not seek pipes which cause more issues.

> PS: I'll raise 2 minor issues now, but these can wait.

No problem, all issues are welcome, they help me and other users. Please also try with CI builds, there are usually fixes and improvements there.

**Comment by chros73** [comment]
> It does not on itself, but its usefull ...

Oh, you're right! :) I modified the qaac template to have the `--normalize` option, so that's why it always created a temp `wav` file with `mp3` inputs. By bad, sorry. :)

Ok, so the proper solution for me is to create (by duplicating) a new template for no-pipe required scenarios, with the name e.g.: `M4A (MPEG-4/AAC) - qaac - no-pipe`

> Please also try with CI builds ...

OK, will do, thanks!

**Comment by chros73** [comment]
> ... to create (by duplicating) a new template for no-pipe required  ...

I found an issue with duplicating template (both with v3.1 and b1680):
- duplicate `M4A (MPEG-4/AAC) - qaac` template
  - disable pipes, add FLAC to input extensions
- then try to use it:
  - it will still create a wav file with FLAC input
  - so, it means the settings are somehow still connected with the original template

**Comment by wieslawsoltes** [comment]
@chros73 The important part is format `Id` and order of formats. The program searches for encoder/decoder format using `Id` and uses the first from the formats list. So if you want to use your duplicated template simply move it up in formats list before the original. Other solution is to change format  `Id`.

**Comment by chros73** [comment]
> Other solution is to change format Id.

Oh, I missed that part as well! Sorry, my bad. :)

**Comment by chros73** [comment]
Wieslaw, it's not related to this issue, but just popped in my mind:
since you properly create/label "tickets" for everything, you can generate a changelog file from them.

E.g. This [changelog](https://github.com/chros73/rtorrent-ps-ch/blob/master/CHANGELOG.md) file is generated by [github changelog generator](https://github.com/skywinder/Github-Changelog-Generator) if you have already created issues (tickets), properly labelled them and set them into a milestone; and you can copy-paste it into the release notes, that's the [config](https://github.com/chros73/rtorrent-ps-ch/blob/master/.github_changelog_generator) I use for it.

If you like it use it and feel free to ask about it. :)

**Comment by wieslawsoltes** [comment]
@chros73 Thanks for this. I was thinking about automating this task, but I prefer to have changelog created by hand. My issues not always are good indicator of higher level changes made in project.

**Comment by chros73** [comment]
I understand this, that's why it has a directive in its config called: [exclude-labels](https://github.com/chros73/rtorrent-ps-ch/blob/master/.github_changelog_generator#L4)
Of course you have to go through all your existing issues (even closed ones as well) and add those labels to it.
