### ISSUE TITLE
User defined templates will be overwritten during manual update

### ISSUE THREAD

**Issue by chros73** [wieslawsoltes/BatchEncoder#155]
How to reproduce:
- download and extract the portable version somewhere
- e.g. duplicate and modify a template under Configure Formats
  - it will be saved correctly
- download and extract another portable version on top of the previous one
  - the previously created template is gone :)

Possible solution:
- user templates per category can go into a separate xml file
- application will merge the global and user settings into one during app startup 

Tested with v3.0.

**Comment by wieslawsoltes** [comment]
@chros73 I am aware of this. Did not found good solution so far. Will have to try different approach.

**Comment by chros73** [comment]
No problem, this can wait.

You can check out how [MeGUI](https://sourceforge.net/projects/megui/) handles this kind of stuff, maybe it will be suitable for you as well.

**Comment by wieslawsoltes** [comment]
@chros73 

Can you test this build: https://ci.appveyor.com/project/wieslawsoltes/batchencoder/build/1688/artifacts

I have changed how config is loaded and saved.

**Comment by chros73** [comment]
Sure, thanks, I'll test it tomorrow evening.
My test case will be with b1688:
- duplicate a template and preset then exit
- overwrite the dir with b1688 and check whether the above template / preset is present

Is it good this way?

**Comment by wieslawsoltes** [comment]
Make sure to change format Id.

**Comment by chros73** [comment]
:) I will, I learned the lesson.

**Comment by chros73** [comment]
> - duplicate a format (change ID) and preset then exit
> - overwrite the dir with b1688 and check whether the above new format / preset is present

Didn't work, my new preset and format is gone.

**Comment by wieslawsoltes** [comment]
The issue is that I wanted to have possibility to change order of formats, to have this I somehow have to store this in config file, but on other hand I also want to have updates. Currently I can no find the solution to have both working.
I have changed `Formats.xml` file to have only list of format Id's and store the actual formats  in separate files. So your new config is only lost from `Formats.xml` but actually is saved in `fromats` folder with file name `<your format Id>.xml`.

**Comment by chros73** [comment]
Also, it would be a good idea if when a format is duplicated the app can auto-create:
- a new ID for it (e.g. appending a number to it, or the `_C` as copy)
- a new name for it (e.g. appending ` - copy` to it)
  - this can also apply to preset names and tools name

**Comment by wieslawsoltes** [comment]
I am considering removal of `Formats.xml` and `Tools.xml` and using per format and per tool files discovered in `formats` and `tools` folder. But this solution will remove ordering functionality.

**Comment by chros73** [comment]
> The issue is ...

Thanks for the explanation, I'll take a look and try to think about it later. :)

**Comment by chros73** [comment]
> But this solution will remove ordering functionality.

That's not good. :)
What about having a property for each format, e.g. called `order` (it's an integer)? (I haven't looked at the xml files yet.)
Let's think about it first :)

**Comment by wieslawsoltes** [comment]
@chros73 I think priority would be better.

I would sort by format type first and than by format priority.

**Comment by wieslawsoltes** [comment]
@chros73 
The order of formats would be sorted by two values, first by priority value (P: the higher number means closer to top of the list), than by type (T = encoder->0, decoder->1) .

So something like this:
| T | P |
| 0 | 1 |
| 1 | 2 |
| 0 | 2 |
| 0 | 3 |
| 1 | 1 |

Would result in sorted formats:
T0:P3
T0:P2
T0:P1
T1:P2
T1:P1

So you have encoder first, than decoder (as it is currently), than encoders and decoder sorted by there priority. You move up/down formats by changing the priority value.

**Comment by wieslawsoltes** [comment]
@chros73 I have created separate issue to track the progress of priority based sorting for formats and tools: https://github.com/wieslawsoltes/BatchEncoder/issues/158

**Comment by chros73** [comment]
> So your new config is only lost from Formats.xml ...

You're right, thanks, it's indeed in formats directory.

> ... using per format and per tool files discovered in formats and tools folder ...
formats would be sorted by two values, first by priority value ..., than by type ...

Sounds good, thanks!

**Comment by wieslawsoltes** [comment]
@chros73 If you have time you can test this version:

https://ci.appveyor.com/project/wieslawsoltes/batchencoder/build/2025/artifacts

Hopefully all related issues are fixed.

**Comment by chros73** [comment]
Thanks. How should I test this?

**Comment by wieslawsoltes** [comment]
Download latest CI build, create or duplicate tool or format. Unpack again and check if new configuration is still there.

**Comment by chros73** [comment]
Thanks, and sorry for the late reply: it's working :)

I created 1 new preset and 2 new formats with b2025 and I overwrote it with latest b2045.
I'll start to use the latest build (b2045) from now on, I'll let you know if I will come up with anything unexpected.

**Comment by chros73** [comment]
Thanks and congrats for the new release! Performance improvement is also noticeable. :)

**Comment by wieslawsoltes** [comment]
@chros73 Thanks!
