### ISSUE TITLE
Avast antivirus checks and sends exe home for checking further since v3.1

### ISSUE THREAD

**Issue by chros73** [wieslawsoltes/BatchEncoder#156]
It also doesn't let you use the app. :)
I didn't have this issue with v3.0 (b1680 also has this problem).

Dirty fix: disable protection for 10 minutes in Avast :)
- this way it allows you to use it

Free Avast version: 17.9.2322 (build 17.9.3761.278)

**Comment by wieslawsoltes** [comment]
I had some false positives previously with Virus Total but did manage to change build settings. Seems like Avast issue to me.

Nothing special changed between 3.0 and 3.1 releases: https://github.com/wieslawsoltes/BatchEncoder/compare/3.0...3.1

Checked the 3.0 and 3.1 (Win32 and x64) and all seems ok.

https://www.virustotal.com/#/file/b0364efd57923d43ba6f17450d6ee323109c1b5e5fd9f9a6feeff061b644bd33/detection

https://www.virustotal.com/#/file/c6f1b8f709793ba59b1623dded9bff218e2d368cef0a1ad2a36204432f2798fe/detection

https://www.virustotal.com/#/file/be27438ca84400cda13b4cfb6e171f77ee51b7c061886bb70ea1775711a81240/detection

https://www.virustotal.com/#/file/cc5ebee74ce6e12cd4306f535b0dae8f38dc6d34e80bfcbfe59a590f564f2f1e/detection

Also checked latest build and also ok.

https://www.virustotal.com/#/file/6e9ac4b16b233a3c0d0225619e76861f0cd362b755a621103b2f6cf938b29903/detection

https://www.virustotal.com/#/file-analysis/MjQ2ODIwMjAwODYzN2ZhYzMzNzkzMDk2ODIyMGY2NDU6MTUxNzA3NzM0MQ==

**Comment by chros73** [comment]
> Seems like Avast issue to me.

I'm pretty sure it's OK. I just wanted you and other users to know that this can happen.
Feel free to close this issue if you want to.
