### ISSUE TITLE
How to create multiple tracks from flac + cue files with qaac?

### ISSUE THREAD

**Issue by chros73** [wieslawsoltes/BatchEncoder#159]
It almost worked: but it overwrites the same output m4a file.

This is what I tried:
- duplicate qaac format:
  - name: `M4A (MPEG-4/AAC) - qaac - nopipe - cue-single`
  - id: `QAAC_M4A_NOPIPE_CUESINGLE`
  - Input extensions: `WAV,FLAC,CUE`
  - pipes: unselected both
  - cmd-line template: `$EXE $OPTIONS --copy-artwork --ignorelength --fname-format "${tracknumber}${artist& }${artist} -${title& }${title}" $INFILE  -o $OUTFILE`

This one works with qaac in command line:
`\BatchEncoder-x64\tools\qaac_2.64\qaac_2.64\x64\qaac64.exe --tvbr 91 --copy-artwork --normalize --fname-format "${tracknumber}${artist& }${artist} -${title& }${title}" *.cue`

I understand that it's a special case, but maybe I just missed some settings :)
Thanks!

**Comment by wieslawsoltes** [comment]
@chros73 Try removing from cmd-line template this part ` -o $OUTFILE`

**Comment by chros73** [comment]
Thanks I tried that:
- it didn't create any files in the output dir then (with default selection of output dropdown above the statusbar)
  - I also tried to set this dropdown to just "sourcedir", but it didn't help either

It's not really important, I can do those via command line.

**Comment by wieslawsoltes** [comment]
@chros73 I will try to investigate further.

**Comment by chros73** [comment]
I just noticed 1 more thing playing with qaac (not important either):
according to [this page](https://github.com/nu774/qaac/wiki/About-input-format): qaac accepts raw PCM, WAV, ALAC, MP3, AAC(LC)...
It indeed works with mp3 and m4a inputs via commandline.

So, (all the pipe settings are unset) I modified input extensions to: `WAV, MP3, M4A`:
- mp3 is working well
- but m4a input is overwritten by its output (for obvious reasons)
  - qaac handles this by putting an extra underscore after the original name: `foo.m4a` -> `foo_.m4a`

**Comment by wieslawsoltes** [comment]
@chros73 You can disable overwriting files by setting `OverwriteExistingFiles` to false from options menu. 

I like idea to change output file name if it already exists. I will consider adding such option.
