### ISSUE TITLE
Add relative output path support

### ISSUE THREAD

**Issue by wieslawsoltes** [wieslawsoltes/BatchEncoder#166]

**Comment by chros73** [comment]
Woow! You're working hard! :) Thanks Wieslaw!
I use v3.1 in the last month almost every day, it's a really amazing tool! Thanks!

**Comment by wieslawsoltes** [comment]
@chros73 Yeah been working a lot.

There are more changes planned for output path: https://github.com/wieslawsoltes/BatchEncoder/issues/152

You can try latest test builds here: https://ci.appveyor.com/project/wieslawsoltes/batchencoder/build/artifacts

**Comment by wieslawsoltes** [comment]
@chros73 You can also do stuff like this: 

`D:\DOKUMENTY\WEB\TEMP\WAV\converted\2018-03-02\$Ext$\$Name$\$Name$.$Ext$`

The output path variables are replace on all occurrences.

**Comment by chros73** [comment]
Nice!

> You can try latest test builds here

I'd rather wait for a release version or a beta. I know all the quirks of v3.1 now and it's freaking awesome!

**Comment by wieslawsoltes** [comment]
> I'd rather wait for a release version or a beta. I know all the quirks of v3.1 now and it's freaking awesome!

No problem. I have few issues to solve before next release https://github.com/wieslawsoltes/BatchEncoder/milestone/11

**Comment by chros73** [comment]
No worries, take your time. And have a good weekend!
