### ISSUE TITLE
Add option to trim audio

### ISSUE THREAD

**Issue by bebetoalves** [wieslawsoltes/BatchEncoder#169]
Would you add a function to trim the audio? I usually do this in MeGUI using a .clt file with the FPS, start and end frame.

Usually this .clt file is like this:

```
<?xml version="1.0"?>
<Cuts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Framerate>23.976023976023978</Framerate>
  <Style>NO_TRANSITION</Style>
  <AllCuts>
    <CutSection>
      <startFrame>0</startFrame>
      <endFrame>33804</endFrame>
    </CutSection>
  </AllCuts>
</Cuts>
```

**Comment by chros73** [comment]
I don't think it's possible with this tool what you want:
- MeGUI uses AviSynth to deal with these kind of things
- this tool uses the binaries themselves

So, what you can do is:
- you have to check whether a given tool supports that feature you're looking for (in this case trimming)
- if it does (and you tried out via command line), then you can create (duplicate) a new profile for it and include that switch what you used
- then use that profile during transcoding

**Comment by wieslawsoltes** [comment]
@chros73 Revavi tool supports .avs input than can be fed into other encoder as .wav.

https://github.com/wieslawsoltes/BatchEncoder/blob/master/config/formats/REWAVI_AVS_WAV.xml#L2

**Comment by wieslawsoltes** [comment]
@bebetoalves As @chros73 pointed out program itself does not do any processing, it uses external command-line tools. You can try using Avisynth scripts and add them to the items list.

**Comment by chros73** [comment]
> Rewavi tool supports .avs input

Oh, nice one, thanks! :)

**Comment by wieslawsoltes** [comment]
@chros73 I have forked old project and updated. https://github.com/wieslawsoltes/rewavi
