### ISSUE TITLE
No output is visible in Console window

### ISSUE THREAD

**Issue by chros73** [wieslawsoltes/BatchEncoder#192]
No output is visible in Console window:
- option "Hide console window" is disabled
- tried out with lame and qaac-lc encoders

**Comment by wieslawsoltes** [comment]
The output is redirected to BatchEncoder stderr stream so it can parse output. I am planning to add logging support so you can check the console output.

**Comment by chros73** [comment]
That would be perfect, thanks.

**Comment by wieslawsoltes** [comment]
@chros73 You can track progress here https://github.com/wieslawsoltes/BatchEncoder/issues/171.

**Comment by chros73** [comment]
Thanks, then I'm closing this issue.
