### ISSUE TITLE
[Feature Request] Keep original file's metadata to newly encoded file

### ISSUE THREAD

**Issue by ghost** [wieslawsoltes/BatchEncoder#194]
Hello. I'd like to request a new feature. Would it be possible for the next release of BatchEncoder to be able to pass the original file's metadata to the encoded file? I like to convert music files (mp3, m4a, FLAC) from one format to another but BatchEncoder doesn't pass metadata, cover art to the new encoded file, I find it a very important feature. Please consider my request.
Thank you.

**Comment by wieslawsoltes** [comment]
It's not planned currently.
