### ISSUE TITLE
Any chance to add qaac for ALAC?

### ISSUE THREAD

**Issue by bezik46** [wieslawsoltes/BatchEncoder#2]
https://sites.google.com/site/qaacpage/cabinet

sebus

**Comment by wieslawsoltes** [comment]
@scerazy Yes, its on my ToDo list https://github.com/wieslawsoltes/BatchEncoder/wiki/ToDo

You can try adding it yourself, just define new format (use one of the existing as template) in config file: https://github.com/wieslawsoltes/BatchEncoder/blob/master/config/BatchEncoder.config#L209 using this command-line option as reference https://github.com/nu774/qaac/wiki/Command-Line-Options 

qaac does support `"-" as infile means stdin` so adding support for encoding would be very easy.

Currently adding new formats in GUI is not implemented.

**Comment by wieslawsoltes** [comment]
@scerazy Added new output format definition `ALAC (Apple Lossless)`, latest CI builds should be available for testing.

Format definition:
```XML
<Format id="ENC_ALAC" name="ALAC (Apple Lossless)" template="$EXE $OPTIONS --ignorelength $INFILE -o $OUTFILE" input="true" output="false" function="- none -" path="qaac.exe" type="0" formats="WAV" extension="M4A" default="0">
    <Presets>
        <Preset name="ALAC encoding mode" options="--alac" />
    </Presets>
</Format>
```

**Comment by wieslawsoltes** [comment]
Tested with qaac 2.62 and its working.
