### ISSUE TITLE
Images (like cover art) are added to conversion list when dropping directory on window

### ISSUE THREAD

**Issue by Fironet** [wieslawsoltes/BatchEncoder#54]
When drag and dropping directories onto the BatchEncoder window any images present are added to the list to be converted. Is there a way to limit input files to audio only, perhaps via a whitelist config option?

![screenshot](https://cloud.githubusercontent.com/assets/6971981/23130227/b7a03630-f7d9-11e6-9bcc-1f0467adaf0b.png)

**Comment by wieslawsoltes** [comment]
Currently all files are added. I will fix this soon.

**Comment by wieslawsoltes** [comment]
@Fironet Fixed. You can control this in Options menu by setting `Validate Input Files` option. Currently you can use latest CI builds https://ci.appveyor.com/project/wieslawsoltes/batchencoder/build/artifacts for testing. This will be part of v1.3 release.

**Comment by Fironet** [comment]
That was surprisingly quick. Appreciated!
