### ISSUE TITLE
Advanced output options

### ISSUE THREAD

**Issue by Fironet** [wieslawsoltes/BatchEncoder#55]
One thing I've always found useful of certain programs like Mp3Tag and CUERipper is the ability to enter custom output structures, such as outputting to relative paths and directories named after audio tags.

Examples might be entering `\Converted` in the output path for creating/saving to a directory within the source directory, or `E:\Music\%albumartist%\%year% - %album%` for outputting to a dynamically set path based on tags. I've found such output options help immensely in organizing files and reducing time on tasks like manually entering outputs for each operation.

Loving the simplicity and snappiness of the front end btw. I can easily see it replacing my use of LameXP in the future.

**Comment by wieslawsoltes** [comment]
I agree this is useful, but currently there is no support for tags builtin. To make this work it would require reading file tags (for each supported input format) and map those tags to output pattern. I do not want to add any external .dll dependencies, so only option is to have command-line tool (more realistically many tools e.g. for flac, wavpack, m4a etc.), that can output file tag data to `stdout` so `BatchEncoder` can capture it and than I would have map the output to common tag format like `%year% - %album%` etc. My plan is first to add Lua scripting support and than command-line tag tools supports, after that we will see what would be possible.

**Comment by Fironet** [comment]
> I agree this is useful, but currently there is no support for tags builtin. My plan is first to add Lua scripting support and than command-line tag tools supports, after that we will see what would be possible.

I see. Would relative paths be able to added at least in the near-future, so one could auto output to a directory located in that of the source files?

For example, adding a directory in BatchEncoder such as `E:\Music\SomeAlbum`, then setting the output path as `\Converted` (or even with some variable like `%currentdirectory%\Converted`) which could output to `E:\Music\SomeAlbum\Converted`.

Would this be possible? As currently when the Output path is unchecked it does output to the source directory but its mixed in with the source files and being able to output to a dedicated folder located beside to the source files would be great.

**Comment by wieslawsoltes** [comment]
I would prefer something like:
```
$SourceDirectory$\$Name$.$Ext$
```
or shorter version:
```
$Name$.$Ext$
```
or another version:
```
$SourceDirectory$\Converted\$Name$.$Ext$
```
or another shorter version:
```
Converted\$Name$.$Ext$
```
custom output path:
```
C:\Output\Path\$Name$.$Ext$
```

**Comment by Fironet** [comment]
Sounds good. I'm guessing the `$Name$.$Ext$` is a way that allows for optionally altering the output filenames per file? Such as `$SourceDirectory$\$Name$_converted.$Ext$`?

**Comment by wieslawsoltes** [comment]
@Fironet Yes exactly. The `$Name$` and `$Ext$` variables are replaced with item `Name` and `output format extension` and the rest of text is preserved. I will do some experimental implementation and will see what works best, will share the results here.

**Comment by wieslawsoltes** [comment]
@Fironet I have implemented advanced output path options as described below. Please let me know if you have any comment or suggestions. I will have to do more testing before official v1.3 realse and you can also download latest CI builds for testing here: 

https://ci.appveyor.com/project/wieslawsoltes/batchencoder/build/artifacts.

## Output path format

Possible `output path` configurations:

* `""` -> empty string is same as `$SourceDirectory$`
* `$SourceDirectory$` -> same as $SourceDirectory$\\`$Name$`.`$Ext$`
* `$SourceDirectory$`\\`$Name$`.`$Ext$`
* `$SourceDirectory$`\\`$Name$`_converted.`$Ext$`
* `$SourceDirectory$`\\Converted\\`$Name$`.`$Ext$`
* C:\\Output -> same as C:\\Output\\Path\\`$Name$`.`$Ext$`
* C:\\Output\\`$Name$`.`$Ext$`
* C:\\Output\\`$Name$`_converted.`$Ext$`

Variables:

* `$SourceDirectory$` - input file path.
* `$Name$` - input item name.
* `$Ext$` - output format extension.

You can add also custom text inside `output path`.

Valid `output path` configurations:

* If output path is empty only input file directory is used (name and extension are added automatically).
* If `$SourceDirectory$`, `$Name$` and `$Ext$` variables are missing full output path must be provided by user (ignore input file path and variables)
* If `$SourceDirectory$`, `$Name$` and `$Ext$` variables are present input source file path is used with item `Name` and output format extension.
* If `$SourceDirectory$` is missing and `$Name$` and `$Ext$` variables are present item `Name` and output format extension are used (full output path must be provided by user).
* If only `$SourceDirectory$` variable is present input source file path is used (name and extension are added automatically)

**Comment by Fironet** [comment]
Observations using v1.3 (build699 alpha x64). Liking the examples in the Ouput path drop-down. Tested them with various paths and they function as expected. I wonder if the variables should be case-insensitive as when they're written in lowercase they're interpreted as the name of a new directory, though the examples make the proper syntax pretty obvious.

One small bug I found is when the BatchEncoder window is at its mininum (default) width any strings that exceed the length of the visible Output path text field become restricted to new character additions. Not sure what's causing it.

I noticed this with the following example paths which were slightly longer than the visible Ouput path field at the window's default width:

````
$SourceDirectory$\$Name$_converted.$Ext$
$SourceDirectory$\Converted\$Name$.$Ext$
````

Adding to the field doesn't work in such cases. However, after enough existing characters have been deleted with backspace it permits new characters to be added by the user to the field, or after resizing the window to a wider size. Version 1.2 doesn't appear to have this issue in the field at small window widths.

Something else I noticed is there's no overwrite existing files dialog warning but that would be a separate suggestion.

> If $SourceDirectory$ is missing and $Name$ and $Ext$ variables are present item Name and output format extension are used (full output path must be provided by user).

I've found this writes to the BatchEncoder directory when only `$Name$.$Ext$` is present in the Output path. Not sure if that's meant to be the expected behavior.

**Comment by wieslawsoltes** [comment]
@Fironet 

Output path issues are fixed in the latest CI builds.

I have also  added option to enable/disable overwrite existing files, also available in the latest CI builds..

Regarding the behavior of output path when only $Name$.$Ext$ is present, I have updated Readme with `if not program writes output files to the BatchEncoder directory`. This is intended behavior, using only $Name$ and $Ext$ variables is generally not recommended because program can not determine what the output path should be other than BatchEncoder.exe directory.
