### ISSUE TITLE
Add the ability to trans-code audio streams within video files

### ISSUE THREAD

**Issue by wieslawsoltes** [wieslawsoltes/BatchEncoder#63]
For example in mp4/mkv container.

* https://github.com/leandromoreira/ffmpeg-libav-tutorial/blob/master/README.md
* https://www.ffmpeg.org/ffmpeg.html
* http://slhck.info/ffmpeg-encoding-course/#/

**Comment by Metaphorce812** [comment]
This would be really helpful. It could be done using ffmpeg (demux the audio to a temp file, then remux the converted audio with the original non-converted streams (e.g., video, subtitles, chapters, other audio streams that weren't converted), but unfortunately I don't have the knowledge of ffmpeg to help you out. MKVToolNix would be another option too.
