### ISSUE TITLE
If encoder can't be found drag and drop doesn't function

### ISSUE THREAD

**Issue by Fironet** [wieslawsoltes/BatchEncoder#64]
Discovered that dragging and dropping music files on the main window doesn't work if the binary for the selected encoder can't be found at the path specified in the Configure Formats settings.

To reproduce change the path of the selected encoder to something that doesn't exist in Configure Formats (in my case I accidentally made the path `\Binaries\lame.exe` rather than `Binaries\lame.exe`), relaunch BatchEncoder then try dragging directories/files.

Stumbled upon this as I found that launching beta versions of BE in a separate directory seems to cause the main BE directory's settings file to change, resetting the custom encoder paths, so I usually update all the paths in a text editor.

**Comment by wieslawsoltes** [comment]
@Fironet I could not reproduce the drag and drop issue when encoder binary is missing. What system are you running on?

**Comment by Fironet** [comment]
Running BE v1.3 on Windows 8.1 Pro. Maybe it has to do with specifically the back slash at the start of the path?

Edit: I now can't seem to reproduce it, either. That's strange, as when I originally posted it it could be reproduced twice in a row.

**Comment by wieslawsoltes** [comment]
@Fironet I'm on Windows 10 Pro and I'm not able to reproduce the issue. The executable path does not have any connection with drag and drop code. There must be some other variable that I'm missing here, see below my attempt to reproduce the issue:

![2017-04-15_00-34-50](https://cloud.githubusercontent.com/assets/2297442/25057829/aab339e0-2173-11e7-8689-3832e65f52c9.gif)

**Comment by Fironet** [comment]
Guess I'll just close the issue in that case. Thanks for looking into it.
