### ISSUE TITLE
Samba network path suport.

### ISSUE THREAD

**Issue by harbinbeer** [wieslawsoltes/BatchEncoder#65]
Can be inputted but can't to be outputted.
Please fix this, thank you.

**Comment by wieslawsoltes** [comment]
@harbinbeer What is path you are inputting and what formats have you used?

**Comment by wieslawsoltes** [comment]
This can be limitation of command-line tools not supporting network path.

**Comment by harbinbeer** [comment]
You're right, That's Wavpack's issue.
I've tried run wavpack.exe in cmd, doesn't support network path. with '\\' prefix.
Sorry.
