### ISSUE TITLE
Error: can not create command-line process (2)

### ISSUE THREAD

**Issue by bezik46** [wieslawsoltes/BatchEncoder#66]
That is all I get while running it.

https://s9.postimg.org/h9hnz7gn3/can_not_create_command_line_process.png

**Comment by wieslawsoltes** [comment]
You need to download tools and configure formats https://github.com/wieslawsoltes/BatchEncoder#tool-downloads

**Comment by bezik46** [comment]
I have done that!
It applies also to decoder (if the input is not wav)! It would be better to have some better error.
I had encoder configured, but not decoder! Works now, thanks
