### ISSUE TITLE
Show birate for AAC default VBR presets

### ISSUE THREAD

**Issue by dragons4life** [wieslawsoltes/BatchEncoder#68]
This is the way foobar shows it, however this program is different and doesn't have a slider and relies on names, which I am fine with, however It would be much better if the presets for True VBR Quality had their bitrates on their names (unless I am reading wrong and it's actually 109kbps~)

Foobar2K
<img src='https://i.imgur.com/UYW7WMK.png'/>
BatchEncoder
<img src='https://i.imgur.com/6Q588WK.png'/>

**Comment by wieslawsoltes** [comment]
@dragons4life You can use `Configure presets` dialog to change preset names for your liking. https://github.com/wieslawsoltes/BatchEncoder#configure-presets

You can load and save presets, load and save format too. 

Default formats are here: https://github.com/wieslawsoltes/BatchEncoder/tree/master/formats/encoder and here https://github.com/wieslawsoltes/BatchEncoder/blob/master/config/BatchEncoder.formats you can edit both for you liking too.

If you are interested you can edit above formats and presets and submit PR with changes.

**Comment by dragons4life** [comment]
Do I have to edit both or just one? I couldn't find the kbps for AAC Nero's "quality 0.00" and also don't know which of the aac encoders is FAAC, doesn't look to be like FDK's, is it the ffmpeg one?

**Comment by wieslawsoltes** [comment]
AAC Nero's "quality 0.00" 

https://github.com/wieslawsoltes/BatchEncoder/blob/master/config/BatchEncoder.formats#L203
https://github.com/wieslawsoltes/BatchEncoder/blob/master/config/BatchEncoder.formats#L385

https://github.com/wieslawsoltes/BatchEncoder/blob/master/formats/encoder/NERO_M4A.format#L4
https://github.com/wieslawsoltes/BatchEncoder/blob/master/formats/encoder/NERO_MP4.format#L4

Please edit both. Copy and paste from `format` file to `config/BatchEncoder.formats`.

Please also check the indentation to be same as original. I have corrected it in your previous PRs.

**Comment by wieslawsoltes** [comment]
@dragons4life Ok I have fixed PRs indentation. Please do not make any changes (you can, but you need update your branches).

**Comment by dragons4life** [comment]
For some reason I though the indentations would of just add by themselves thanks for adding them and sorry don't really know much about github and whatnot, what do you mean by updating my branches?

**Comment by wieslawsoltes** [comment]
I have made changes in your git PR branches. You need to `pull` changes to sync git branches, otherwise you will get errors. But if nothing more is to changes leave them as is and I will merge them to my `master` branch. After that you can delete patch branches.

**Comment by dragons4life** [comment]
Did that do the trick? thanks for helping me on this github journey

**Comment by wieslawsoltes** [comment]
No problems. I have merged your PR into master branch. Thank you for contribution. It will be part of v1.4 release.

After CI builds finish you can download nightly version here https://ci.appveyor.com/project/wieslawsoltes/batchencoder/build/artifacts
