### ISSUE TITLE
"Error: can not create command-line process (2)"

### ISSUE THREAD

**Issue by dragons4life** [wieslawsoltes/BatchEncoder#74]
It seems that any format I choose gives me this error regardless of the files, is there a way to post a log?
I am using the latest version, it happens for every file I try to convert.

**Comment by wieslawsoltes** [comment]
You have to download command-line tools https://github.com/wieslawsoltes/BatchEncoder/blob/dev/README.md#tool-downloads and Configure formats https://github.com/wieslawsoltes/BatchEncoder/blob/dev/README.md#configure-formats to set command-line tools executable paths.

**Comment by dragons4life** [comment]
I did what was shown in your video (in the wiki) and I have even added multiple encoders to my path on windows, somehow I don't think it's your GUI causing the issue, for some reason all the encoders under my CMD end up giving me "Error parsing input file: filename.extension" or metadata blocks errors for flac.
I've tried searching on the internet for how to fix these errors but nothing has appeared.

**Comment by wieslawsoltes** [comment]
@dragons4life Try putting some command-line encoder in same folder as BatchEncoder or different path (or disk) and configure path from GUI and check if error occurs. The error message you are getting is that BatchEncoder  can not find encoder .exe in path you have provided. So this my be some permissions issue (no access to this directory), invalid path or some AV software is messing this up in your system.

**Comment by dragons4life** [comment]
@wieslawsoltes Actually the issue was the file I was encoding apparently was broken, after restarting my computer (probably because sometimes PATH(S) need the computer to restart to work on windows or using refreshenv) everything seem to work fine, but it's odd because I couldn't encode any other files either even while the CMD detected the encoders and using the CMD.

Oh well, a random restart worked that's all I know. thanks for helping me.
