### ISSUE TITLE
Add .mka support

### ISSUE THREAD

**Issue by dragons4life** [wieslawsoltes/BatchEncoder#98]
This might be a bit difficult since the container can contain multiple audios, in which case I suggest converting all.

**Comment by wieslawsoltes** [comment]
@dragons4life Did you try with `ffmpeg`?

**Comment by dragons4life** [comment]
It doesn't let me drag the file/add it to the list, It can probably easily be encoded with ffmpeg.

**Comment by wieslawsoltes** [comment]
Try importing this format: https://github.com/wieslawsoltes/BatchEncoder/blob/master/config/formats/FFMPEG_MKA_WAV.format

**Comment by dragons4life** [comment]
Yeah that worked, the problem is that the latest version (2.1) don't allow you to drag and drop .mka files.
Using the latest alpha did work.

**Comment by wieslawsoltes** [comment]
@dragons4life It does not allow to drag and drop because it checks if the extension is supported by encoder/decoder. This will be released as part of v2.2.
